markdown:       rdiscount
safe:           true
lsi:            false
highlighter:    pygments
permalink:      /:year/:month/:day/:title.html
author:		Holbrook(wanghaikuo@gmail.com)
title:          心内求法
url:            http://holbrook.github.io
description:    "Holbrook's blog"
feed:           /atom.xml

menuitems:
    - title:     首页
      url:      /index.html
    - title:     分类 
      url:      /categories.html
    - title:     归档
      url:      /pages/archives.html
    - title:     标签
      url:      /pages/tags.html
    - title:     关于
      url:      /pages/about.html
